github.com:
    users:
        JRPlayersCE:
            oauth_token: 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
    git_protocol: https
    user: JRPlayersCE
    oauth_token: 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
