l seek 5             # Seta pra direita / Avança 5 segundos
h seek -5            # Seta pra esquerda / Retrocede 5 segundos
k add volume 2       # Aumenta volume
j add volume -2      # Diminui volume
SPACE cycle pause    # Barra de espaço pausa/despausa
