# Força a janela a abrir mesmo jogando apenas arquivos de áudio
force-window=yes

# Adicione o símbolo # no início desta linha:
# lavfi-complex="[aid]asplit[a][b];[a]showcqt=s=1280x720:bar_h=40:count=5[v];[b]anullsink"

# Ativa o visualizador nativo em ondas (muito mais leve e estável)
show-profile=wave


# Customização da janela e OSD (Interface na tela)
osd-font="JetBrainsMono Nerd Font"
osd-font-size=24
osd-color="#a7c080" # Cor verde suave (Everforest)
osd-border-color="#2d353b"
