local _pprint = require("./pprint.lua")
PS = function(...)
    hl.dsp.exec_cmd('notify-send ' .. _pprint(...))
end

hl.config({ autogenerated = false })

hl.monitor({
    output = "desc: AU Optronics 0x233C",
    mode = "1366x768@60.04100",
    position = "auto",
    scale = "1",
})

hl.monitor({
    output = "desc: UGD CD120FH 20210617",
    mode = "preferred",
    position = "auto",
    scale = "1.5",
})

hl.monitor({
    output = "desc: LG Electronics LG ULTRAWIDE 0x0002C544",
    mode = "2560x1080@75",
    position = "auto",
    scale = "1",
})

local root_terminal = "kitty"
local terminal = root_terminal .. " fish"
local system_monitor = terminal .. " -C 'btop'"
local fileManager = terminal .. " -C 'y'"
local browser = "flatpak run app.zen_browser.zen"
local menu = "rofi -show drun"
local open_waypaper = "killall waypaper; waypaper --zen-mode"

hl.on("hyprland.start", function()
    hl.exec_cmd("waypaper --restore")
    hl.exec_cmd("discord")
    hl.exec_cmd("waybar")
end)

hl.on("workspace.active", function(workspace)
    print(workspace)
end)

hl.env("XCURSOR_THEME", "everforest-cursors")
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_THEME", "everforest-cursors")
hl.env("HYPRCURSOR_SIZE", "24")

require("./theme.lua")

hl.config({
    general = {
        layout = "scrolling",
    },
})

hl.config({
    master = {
        new_status = "master",
    },
    dwindle = {
        preserve_split = true,
    },
    scrolling = {
        fullscreen_on_one_column = false,
        focus_fit_method = 0,
    },

    input = {
        kb_layout = "br",
        kb_variant = "abnt2",
        kb_model = "",
        kb_options = "",
        kb_rules = "",

        follow_mouse = false,

        accel_profile = "flat",
        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

        touchpad = {
            natural_scroll = true,
        },
    },
    cursor = {
        no_hardware_cursors = true,
        no_warps = true,
    },
})

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace",
})

local mainMod = "SUPER"

hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + C", hl.dsp.window.close())
hl.bind(
    mainMod .. " + M",
    hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch 'hl.dsp.exit()'")
)

hl.bind(mainMod .. " + X", function()
    hl.dispatch(hl.dsp.window.resize({ x = 2560, y = 1080 }))
    hl.dispatch(hl.dsp.window.center())
end)
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen({ action = "toggle" }))
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + TAB", hl.dsp.exec_cmd(open_waypaper))
hl.bind("CTRL + SHIFT + ESCAPE", hl.dsp.exec_cmd(system_monitor))
hl.bind("CTRL + SHIFT + S", hl.dsp.exec_cmd("flameshot gui"))

hl.bind(mainMod .. " + W", hl.dsp.focus({ workspace = "r-1" }))
hl.bind(mainMod .. " + S", hl.dsp.focus({ workspace = "r+1" }))
hl.bind(mainMod .. " + D", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + A", hl.dsp.focus({ direction = "left" }))

hl.bind(mainMod .. " + SHIFT + tab", function()
    local layouts = { "scrolling", "dwindle", "master", "monocle" }
    local workspace = hl.get_active_workspace()
    if hl.get_active_special_workspace() then
        workspace = hl.get_active_special_workspace()
    end

    local next_layout = "dwindle"

    if not workspace then
        return
    end

    for i = 1, #layouts do
        if layouts[i] == workspace.tiled_layout then
            local next_layout_idx = (i % #layouts) + 1
            next_layout = layouts[next_layout_idx]
            break
        end
    end

    if workspace.special then
        hl.workspace_rule({ workspace = tostring(workspace.name), layout = next_layout })
    else
        hl.workspace_rule({ workspace = "name:" .. tostring(workspace.name), layout = next_layout })
    end
end)

hl.bind(mainMod .. " + SPACE", function()
    local window = hl.get_active_window()
    if not window then
        return
    end
    hl.dispatch(hl.dsp.window.cycle_next({
        floating = not window.floating,
        tiled = window.floating,
    }))
end, { release = true, description = "Switch focus between tiled and floating windows" })

for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    hl.bind(mainMod .. " + " .. key, hl.dsp.focus({ workspace = i }))
    hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
end

hl.bind(mainMod .. " + CTRL + 1", hl.dsp.workspace.toggle_special("mpv"))

hl.bind(mainMod .. " + SPACE + W", hl.dsp.window.move({ workspace = "r-1" }))
hl.bind(mainMod .. " + SPACE + S", hl.dsp.window.move({ workspace = "r+1" }))
hl.bind(mainMod .. " + SPACE + A", hl.dsp.window.move({ direction = "left" }))
hl.bind(mainMod .. " + SPACE + D", hl.dsp.window.move({ direction = "right" }))

hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true, transparent = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

hl.bind(mainMod .. " + B + prior", hl.dsp.exec_cmd("ddcutil setvcp 10 + 20"))
hl.bind(mainMod .. " + B + next", hl.dsp.exec_cmd("ddcutil setvcp 10 - 20"))

hl.bind(
    "XF86AudioRaiseVolume",
    hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"),
    { locked = true, repeating = true }
)
hl.bind(
    "XF86AudioLowerVolume",
    hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),
    { locked = true, repeating = true }
)
hl.bind(
    "XF86AudioMute",
    hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),
    { locked = true, repeating = true }
)
hl.bind(
    "XF86AudioMicMute",
    hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),
    { locked = true, repeating = true }
)
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), { locked = true, repeating = true })

-- Requires playerctl
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

hl.workspace_rule({
    workspace = "special:mpv",
    animation = "fade",
})

require("./window_rules.lua")
